### ISSUE TITLE
Ability to add web images to Image component

### ISSUE THREAD

**Issue by ianharrigan** [ianharrigan/haxeui#197]
eg:

``` xml
<image resource="http://somewhere/something.jpg" />
<image resource="http://somewhere/something.gif" />
<image resource="http://somewhere/something.png" />
```

**Comment by marcelofrau** [comment]
Doing this, you will make possible to load by XML the external resources. Do you think it can be done also on the direct field resource on the Image component?

Can you make the load of the images to be done in a background way? So you can define an extenal URL witch can take a long time to load and the UI will not freeze because the image (the main problem here can be the size of the image, that is uknown until the url is resolved)

An example of usage in code instead of XML load can be in this way?

```
var image = new Image();
image.resource = 'http://somewhere/something.jpg'
```

**Comment by ianharrigan** [comment]
Yeah, thats the plan, it should work with css, xml and code. I dont really things its that complicated, for the first iteration it will just be as simple as finding the "http://" and grabbing from there and displaying a place holder, later ftp:// and file:// might be nice also (although file:// would only be for native non-flash targets)

Cheers,
Ian

**Comment by marcelofrau** [comment]
That's great :D

**Comment by ianharrigan** [comment]
![images](https://cloud.githubusercontent.com/assets/3024242/6790976/dc6ac33c-d1ab-11e4-98e5-c426a85ffe46.png)

All supported file types can be loaded over http now (on all platforms)

**Comment by ianharrigan** [comment]
http://haxeui.org/try.jsp?layoutId=bnExr4q

**Comment by bigp** [comment]
Is there a way to load images locally at runtime for the Flash target?

I'm trying to load the resulting SWF in a custom `Animate CC`'s WindowSWF panel. It reads the `ui.xml` correctly, looks like it loads images from external `http://...` addresses fine, but I can't figure out the URL/URI syntax to load it relative to the SWF (ex: `./test.png` doesn't work).

Is this possible to do?

**Comment by bigp** [comment]
To clarify, here's what I'm trying to achieve:
![HaxeUI Image Loading at Runtime](https://i.imgur.com/xbVDCpW.png)

**Comment by ianharrigan** [comment]
Hi, any chance you could zip up your test project  so i can take a look?

**Comment by ianharrigan** [comment]
oh, hang on this is haxeui v1
