### ISSUE TITLE
How do I implement a close-to-tray behavior?

### ISSUE THREAD

**Issue by ShedoSurashu** [ianharrigan/haxeui#209]
I want to make it so that when the user clicks the close button, on Windows and OS X at least, the application minimizes to the tray for Windows or on the menubar for OS X instead of closing. However clicking on the minimize button should still do the default behavior of minimizing the app to the task bar or the dock.

**Comment by Type1J** [comment]
That sounds like an OpenFL or even Lime question.

@ianharrigan Does HaxeUI have it's own way to deal with Minimize/Maximize/Close buttons on the windows of platforms that have them?

**Comment by ianharrigan** [comment]
@Type1J, nope you are right, that is openfl/lime specific. I would assume you could create an extension of some description to do it.

Cheers,
Ian

**Comment by ShedoSurashu** [comment]
Alright, sorry for the misunderstanding. I'll go and post this over at OpenFL then instead.

**Comment by Type1J** [comment]
No problem :-) If you have no luck in OpenFL issues, then you might have to solve this one outside of Haxe as well (in C++). I'll tell you this to get you started:

I believe that "Windows.h" is included in all files compiled from Haxe, so if you can catch the minimize and/or close events by hooking with wndproc (I'll elaborate how to do that if you ask), and catching WM_SIZE with wParam set to SIZE_MINIMIZED, and WM_CLOSE, but calling the old wndproc for all other actions. For either of the above events, you're going to want to call ShowWindow(wnd, SW_HIDE);, and then return 1; (don't call the old wndproc). That should give you the behavior that you described except for the tray icon (I'll also elaborate here if you ask).

As for the mac, it's a bit more complicated because you'll have to drop into Objective C (or Objective C++), which will require a separate file (Haxe code compiles to C++, not Objective C++) instead of just inline C++ code. What you want to do is add a NSWindowDelegate that has a "- (BOOL)windowShouldClose:(id)sender" method and a "- (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication hasVisibleWindows:(BOOL)flag" method. They are called when the user clicks the close button or clicks the app in the dock. As for how to hide and reshow the app, sorry: I forgot that part. :-)

Hopefully, that will get you started, if OpenFL doesn't have a solution.
