### ISSUE TITLE
Does Image supports the ":over" styling?

### ISSUE THREAD

**Issue by kevinresol** [ianharrigan/haxeui#236]
I would like to show the border to indicate a mouseover on an image....

**Comment by ianharrigan** [comment]
It actually doesnt... But i think its a good idea. Ill leave this open and add the over/down states at sompoint soon. 

In the meantime i guess you could use a button? But ill try and get this sorted sooner rather than later as it shouldnt take long.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Quick question, do you think it should only support "over"? What about "down" and "disabled"? 

Im not sure, as my thought is sort of, if you wanted all those states then you would just use a button, no?

**Comment by kevinresol** [comment]
ya, I think button is the better solution.
At the meantime I am able to achieve the thing by hooking a mouseover event to the image and change its stylename in the listener.

**Comment by ianharrigan** [comment]
So its actually not as straight forward as i would have liked to use a button, and there are a few issues (like background transparency), for example:

http://haxeui.org/try.jsp?layoutId=9oy59Rb

But the white border when the button is "normal" shouldnt be white, it should be transparent (ie, grey), so there is a bug there. That can be fixed with the backgroundAlpha style, ie: 

http://haxeui.org/try.jsp?layoutId=EKorRBd

But thats a bit of a hack. Either way, a few things to think about/fix there as i would have liked it to be much easier to create an image button and have the border appear when you mouse over.

**Comment by kevinresol** [comment]
Thanks for the illustration.  Btw, it's off topic but I would like to suggest using typedef to define those option /config objects. Currently they are just Dynamic which makes it hard to figure out what option values are availavle there.

**Comment by ianharrigan** [comment]
Agreed, quite a few things need to stop using Dynamic in general and better type safety etc. ToolTipManager is newer code and is in the right direction (https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/ToolTipManager.hx). Out of interest, what specific config options are you talking about?

**Comment by kevinresol** [comment]
I am still new to haxeui the options I encountered are PopupManager.show,
FileDialogs.show,  Toolkit.open,  etc.
(On mobile now, didn't confirm the exact function name, but you understand
it )

**Comment by ianharrigan** [comment]
Right, yeah, gotcha... Same ones i think should be typed off the top of my head also. 

Nice one,
Ian

**Comment by kevinresol** [comment]
yeah, I love seeing those enums and typedefs in the ToolTipManager!

**Comment by kevinresol** [comment]
Let's focus the efforts on v2
