### ISSUE TITLE
Popup and custom buttons

### ISSUE THREAD

**Issue by DrDerico** [ianharrigan/haxeui#360]
Hi!

When I add custom buttons to the config for building Popup, their callbacks don't invoke. For example:

`showPopup("CONTENT", null, { useDefaultTitle:false, buttons:[new PopupButtonInfo(PopupButton.CUSTOM, "AAA", onDeleteTabConfirmedAAA), new PopupButtonInfo(PopupButton.CUSTOM, "BBB")] }, onDeleteTabConfirmed);`

So, onDeleteTabConfirmedAAA doesn't invoke. I didn't see in haxeui source code any line, that makes deal with PopupButtonInfo "_fn" variable.

**Comment by ianharrigan** [comment]
Yeah, it doesnt seem to be used anywhere, you are right. One thing though i have noticed is you are using PopupButtonInfo and i cant see anywhere that is an input option in: https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/PopupManager.hx#L269

One thing to try is:

```haxe
buttons:[{text: "AAA", fn: onDeleteTabConfirmedAAA}, {text: "BBB"}]
```

ie, use objects rather than `PopupButtonInfo`

**Comment by ianharrigan** [comment]
As we all the method above can you pull latest from haxelib (1.8.21) and try that? Ive added a fix there that should invoke the `.fn` when the button is clicked.

**Comment by DrDerico** [comment]
Ok, I'll try it tomorrow! Thank you very much!!!

**Comment by DrDerico** [comment]
It works!
But if you use objects, you should write code in this way:

`buttons:[{text: "AAA", fn: onDeleteTabConfirmedAAA}, {text: "BBB", fn: null}]`

So all objects must contain the same fields, otherwise compiler gives an error message

**Comment by ianharrigan** [comment]
Right, gotcha... Good to know! Thanks.
